theme = "theme"

[editor]
auto-completion = false
bufferline = "multiple"
color-modes = true
cursorline = true
idle-timeout = 1
shell = ["nu", "--commands"]
text-width = 100
clipboard-provider = "pasteboard"

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline.mode]
insert = "INSERT"
normal = "NORMAL"
select = "SELECT"

[editor.indent-guides]
character = "▏"
render = true
# skip-levels = 1

[editor.whitespace.characters]
tab = "→"

[editor.whitespace.render]
tab = "all"

[editor.soft-wrap]
enable = true

[keys.normal]
b = ":echo %sh{git blame --date=short -L %{cursor_line},+1 %{buffer_name}}"
